### ISSUE TITLE
מסך הגדרות

### ISSUE THREAD

**Issue by Perezari** [YehudaEi/Red-Alarm-Windows#1]
שלום לך ותודה רבה על התוכנה המדהימה הזו, זה עוזר לאשתי לקבל התראות באיזור בו אין אזעקות.
רציתי לדעת האם תוכל להוסיף מסך הגדרות בו אוכל לבחור באילו ערים תהיינה אזעקה, כמו כן, הגדרה נוספת לבחירת צליל אזעקה .. ועוד

**Comment by YehudaEi** [comment]
תודה רבה על הפידבק :)

אני בע"ה מתכנן להוסיף את זה בקרוב, ברגע שיהיה לי זמן אני אוסיף את זה.

**Comment by Perezari** [comment]
אני מפתח בעיקר בשפת C#
אם תרצה אולי להמיר אותה לשפה זו אוכל לעזור לך המון גם ביצירת טבלאות הסטוריה עבור התראות .
זה המייל שלי - ari@avivi.com
צור איתי שם קשר ואעביר לך את הנייד שנוכל לדבר בוואטסאפ.

**Comment by YehudaEi** [comment]
אני לא מצליח לשלוח לך מייל. המייל שלי מופיע בתיאור של הפרופיל שלי.

**Comment by YehudaEi** [comment]
"בקשתך התקבלה"
עכשיו ניתן לסנן ע"פ אזורי התראה
