### ISSUE TITLE
התראות צבע אדום

### ISSUE THREAD

**Issue by Perezari** [YehudaEi/Red-Alarm-Windows#2]
היי יהודה,
יש בעיה בהתראות של הצבע אדום,
עכשיו היו מלא אזעקות אך התוכנה לא דיווחה על כלום.

**Comment by YehudaEi** [comment]
מוזר מאוד, עקרונית לי התוכנה עובדת כמו שצריך, יכול להיות שהאינטרנט היה כבוי או שמישהו כיבה את ההתראות בתוכנה? (אופציה נוספת זה שהאנטי וירוס מחק את התוכנה...)

**Comment by Perezari** [comment]
היי יהודה לאחר כמה זמן זה הסתדר מעצמו.
פשוט נראה לי שהייתה בעיה בעדכונים שלהם בקובץ json יכול להיות.
אין לי אנטי וירוס ואינטרנט היה תקין באותם רגעים, כי קיבלתי התראות מהאתר של פיקוד העורף.
העיקר שהסתדר 😁

**Comment by Perezari** [comment]
נשלח מה-iPhone שלי
